<?php

namespace ContainerRdj12xD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TGKl8LaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tGKl8La' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tGKl8La'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reserverEvent' => ['privates', '.errored..service_locator.tGKl8La.App\\Entity\\ReserverEvent', NULL, 'Cannot autowire service ".service_locator.tGKl8La": it references class "App\\Entity\\ReserverEvent" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'reserverEvent' => 'App\\Entity\\ReserverEvent',
        ]);
    }
}
