<?php

namespace ContainerRdj12xD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2yQ19ccService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2yQ19cc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2yQ19cc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reserverEventRepository' => ['privates', 'App\\Repository\\ReserverEventRepository', 'getReserverEventRepositoryService', true],
        ], [
            'reserverEventRepository' => 'App\\Repository\\ReserverEventRepository',
        ]);
    }
}
