<?php

namespace ContainerRdj12xD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReserverEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tGKl8La.App\Entity\ReserverEvent' shared service.
     *
     * @return \App\Entity\ReserverEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.tGKl8La": it references class "App\\Entity\\ReserverEvent" but no such service exists.');
    }
}
