<?php

namespace ContainerWN3dpgK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_HEUmSgGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.hEUmSgG' shared service.
     *
     * @return \HCaptcha\HCaptcha
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\EvenementController::studentelement()": the $hCaptcha argument is type-hinted with the non-existent class or interface: "HCaptcha\\HCaptcha".');
    }
}
