<?php

namespace ContainerWN3dpgK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4iREZ_FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4iREZ.f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4iREZ.f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'hCaptcha' => ['privates', '.errored.hEUmSgG', NULL, 'Cannot determine controller argument for "App\\Controller\\EvenementController::studentelement()": the $hCaptcha argument is type-hinted with the non-existent class or interface: "HCaptcha\\HCaptcha".'],
        ], [
            'entityManager' => '?',
            'hCaptcha' => '?',
        ]);
    }
}
