<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRdj12xD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRdj12xD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRdj12xD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRdj12xD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRdj12xD\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rdj12xD',
    'container.build_id' => '5e3d4f72',
    'container.build_time' => 1714928820,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRdj12xD');
