<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXx0RcN0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXx0RcN0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXx0RcN0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXx0RcN0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXx0RcN0\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xx0RcN0',
    'container.build_id' => '83340fef',
    'container.build_time' => 1714605711,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXx0RcN0');
